{{- if and .Values.documenso.certificate.enabled (not .Values.documenso.certificate.existingSecret)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "documenso.fullname" .}}-cert
  labels:
    {{- include "documenso.labels" . | nindent 4}}
type: Opaque
# The certificate data would need to be provided during installation
# This is just a placeholder structure
data:
  {{.Values.documenso.certificate.key}}: ""
{{- end}}
