{{- if .Values.postgresql.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "postgresql.fullname" .}}-auth
  labels:
    {{- include "documenso.labels" . | nindent 4}}
    app.kubernetes.io/component: database
type: Opaque
data:
  username: {{.Values.postgresql.auth.username | b64enc | quote}}
  password: {{.Values.postgresql.auth.password | b64enc | quote}}
  database: {{.Values.postgresql.auth.database | b64enc | quote}}
{{- end}}
